### ISSUE TITLE
api.core gets executed N times on first compile and load

### ISSUE THREAD

**Issue by levitanong** [hoplon/hoplon#120] opened 2016-04-06 06:15 UTC
On hoplon-castra

Say you have a comically simple `api.clj`:

``` clj
(ns api-execute-test.api
  (:require [castra.core :refer [defrpc]]))

(println "api called") 
;; N appearances on the terminal means the whole `api.clj` gets called N times.

(defrpc get-state [] {})
(defrpc get-something-else [] {})
```

And you have an `init` in your `rpc.cljs`. If it has N api rpc calls like:

``` clj
...
(defn init []
  (get-state)
  (get-state)
  (get-something-else))
```

The entire `api.clj` gets evaluated N times. In the above case, thrice. 

```
...
Elapsed time: 11.224 sec

api called
api called
api called
```

This becomes especially troublesome if you have database stuff going on like sample data generation. All the data gets N-plicated.

When you trigger a recompile, everything goes back to normal, and `api.clj` is only evaluated once.

```
...
Elapsed time: 12.135 sec

api called
```

For minimal test case, see:
https://github.com/levitanong/api-execute-test
1. clone
2. `boot dev`
3. `localhost:8000`
4. see terminal for printed statements

**Comment by micha** [comment] 2016-04-08 21:22
I can't reproduce this with your repo, it prints `api called` only one time for me...

**Comment by levitanong** [comment] 2016-04-10 09:57
@micha Oh dear. What setup do you have? I'm running OS X El Capitan, MBP Mid-2014.

**Comment by micha** [comment] 2016-04-10 15:39
@levitanong I'm on linux. I can't think of how that namespace could be evaluated multiple times--clojure should only evaluate the namespace the first time it is `require`ed.

**Comment by levitanong** [comment] 2016-04-10 16:17
What distro? My colleague can reproduce it, and he's on Ubuntu. Such an odd bug. @.@

**Comment by levitanong** [comment] 2016-04-11 08:08
So my colleague appears to have found the issue. 
`wrap-castra` "requires" the api on runtime, but if the environment is multithreaded, the call to api happens as many times as there are threads. The workaround he found was to just require it in the `ns` declaration so that it happens predictably on initialization.

**Comment by flyboarder** [comment] 2017-12-27 21:55
Closing as this is directly related to Castra not Hoplon. I have opened up a ticket hoplon/castra#27

**Closed by flyboarder** 2017-12-27 21:55 UTC
Labels: bug
